import type { Metadata } from "next";
import { Cormorant_Garamond, Inter, Space_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/Nav";
import Cursor from "@/components/Cursor";

const cormorantGaramond = Cormorant_Garamond({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["300", "400", "600"],
  style: ["normal", "italic"],
  display: "swap",
});

const inter = Inter({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["300", "400"],
  display: "swap",
});

const spaceMono = Space_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const rustyCourtScript = localFont({
  src: "../fonts/rusty-court-font-duo/RustyCourtScriptDemo-5yJ6G.ttf",
  variable: "--font-rc-script",
  display: "swap",
});

const rustyCourtSerif = localFont({
  src: "../fonts/rusty-court-font-duo/RustyCourtDemoSerif-zrDpD.otf",
  variable: "--font-rc-serif",
  display: "swap",
});

const calisthaDisco = localFont({
  src: "../fonts/CSCalisthaDisco-Regular_demo-BF6a0c2b77166de.otf",
  variable: "--font-calista",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cormorantGaramond.variable} ${inter.variable} ${spaceMono.variable} ${rustyCourtScript.variable} ${rustyCourtSerif.variable} ${calisthaDisco.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Cursor />
        <Nav />
        {children}
      </body>
    </html>
  );
}
